name: RolePlayManager
version: '${project.version}'
main: com.SadJi.RolePlayManager.RolePlayManager
api-version: '1.21.4'
softdepend: [PlaceholderAPI]
commands:
  name:
    usage: /name name surname
    description: change your name
  menu:
    usage: /menu
    description: to open menu
  job:
    usage:  /job
    description: open job list
  setseason:
    usage: /setseason season
    description: set season
  getseason:
    usage: /getseason
    description: get the current season
  call:
    usage: /call name
    description: call somebody
  getday:
    usage: /getday
    description: get current day
  experiment:
    usage: /experiment
    description: just to use
  exptest:
    usage: /exptest
    description: use to upraise level of experiments
  sethex:
    usage: /sethex args
    description: sets hex color of something for a specific player. Better use when target is online
    permission: RolePlayManager.admin
    permission-message: You don't have enough rights
  namecolor:
    usage: /namecolor player hex-color
    description: sets hex color of something for a specific player. Better use when target is online
    permission: RolePlayManager.admin
    permission-message: You don't have enough rights
permissions:
  RolePlayManager.admin:
    default: op
    description: admin perms of the plugin
